name: hondooye_http
description: A useful http package.
version: 1.0.0
repository: "https://github.com/Doohyeon-Kim/hondooye-http.git"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  hondooye_error_handler: ^1.0.0
  hondooye_logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: